# yaml-language-server: $schema=../schema.json
env: []

windows:
  - title: IDE
    leftside:
      cmd: "  nvim"
      working_directory: &fe ../../rex-array-frontend/
    rightside:
      cmd: "  pnpm exec tsc --watch --noEmit --noErrorTruncation"
      norun: true
      working_directory: *fe

  - title: DEV
    # leftside:
    cmd: "  pnpm dev"
    working_directory: *fe

    # rightside:
    #   cmd: "  tools/generate-tree-helper ~/Repositories/open-search-data-loader/initial-tree-v0_2_5.json"
    #   working_directory: *fe
    #   norun: true

  - title: PY
    cmd: "  nvim"
    working_directory: &server ../../rex-array-backend/

  - title: PY
    rightside:
      cmd: "  uv run uvicorn src.ats.main:app --reload"
      working_directory: *server
      norun: true
    leftside:
      cmd: "  docker compose up db"
      working_directory: ../../rex-array-backend/.devcontainer/
      norun: true

  - title: GIT
    rightside:
      cmd: "  git commit --no-verify"
      working_directory: *fe
      norun: true
    leftside:
      cmd: "  git diff --staged --ignore-all-space | delta"
      working_directory: *fe
      norun: true

  - title: DEPLOY
    working_directory: &cdk_dir ../../rex-array-backend/infra/cdk/functions/
    cmd: "  AWS_REGION=me-south-1 pnpm cdk deploy -e ..."
    norun: true

  - title: INVOKE
    working_directory: *cdk_dir
    cmd: "   aws lambda invoke --region me-south-1 --function-name spectrum-migration-runner-spectrummigrationrunnerd-7tvuaaSpJ0HJ /dev/stdout | jq"
    norun: true

  # - title: TREE
  #   leftside:
  #     cmd: "  nvim data-loader.py"
  #     working_directory: &dl ../../open-search-data-loader/
  #   rightside:
  #     cmd: "  python data-loader.py data/ | jq -C | less -R"
  #     working_directory: *dl
  #     norun: true

  # - title: T
  #   leftside:
  #     cmd: "  nvim data/"
  #     working_directory: *dl
  #     norun: true
  #   rightside:
  #     upperside:
  #       cmd: |
  #         < data/full-database-v0_3.json jq \
  #         '.hits.hits.[]._source.chapter_code' | sort -V | uniq -c
  #       norun: true
  #       working_directory: *dl
  #     lowerside:
  #       cmd: python data-loader.py data/ > initial-tree-v0_2_5.json
  #       norun: true
