# yaml-language-server: $schema=../schema.json
env: []

windows:
  - title: IDE
    leftside:
      cmd: "  nvim"
      working_directory: &backend ../../pegasus-backend/
    rightside:
      cmd: "  pnpm exec tsc --watch --noEmit --noErrorTruncation"
      norun: true
      working_directory: *backend

  - title: DEV
    leftside:
      upperside:
        cmd: npm run start

        norun: true
        working_directory: ../../pegasus-backend/user-service/

      lowerside:
        cmd: npm run start

        norun: true
        working_directory: ../../pegasus-backend/admin-service/

    rightside:
      cmd: |
        npm run
      working_directory: ../../pegasus-backend/common/

  - title: TEST
    cmd: "  nvim"
    working_directory: &api ../../pegasus-api-testing/

  - title: INFRA
    working_directory: &infra ../../pegasus-infra/
    leftside:
      cmd: nvim
    rightside:
      cmd: |
        AWS_REGION=me-south-1 pnpm cdk:dev deploy --all --concurrency=10 --require-approval=never
      norun: true

  - title: DB
    leftside:
      cmd: |
        sh ssh-into-instance.sh

      norun: true
      working_directory: ../../pegasus-backend/scripts/

    rightside:
      cmd: |
        PGPASSWORD=UMdnE9UZyaEwJ8e6kVDD psql -p 54320 -h localhost -U postgres

      norun: true
      working_directory: *backend

  - title: ADM
    leftside:
      cmd: |
        nvim
      working_directory: &admin-portal ../../pegasus-admin-portal/
    rightside:
      cmd: |
        npm exec vite -- --port=5174
      working_directory: *admin-portal

  - title: MOCK
    leftside:
      cmd: |
        nvim
      working_directory: &mock-service ../../pegasus-backend/external-service-mock/
    rightside:
      upperside:
        cmd: pnpm run start
        working_directory: *mock-service

      lowerside:
        cmd: curl localhost:8080/api/third-party/season-cal/2025-09-24/2025-09-24 -v | jq | head -n 80
        working_directory: *mock-service

  # - title: GIT
  #   rightside:
  #     cmd: "  git commit --no-verify"
  #     working_directory: *fe
  #     norun: true
  #   leftside:
  #     cmd: "  git diff --staged --ignore-all-space | delta"
  #     working_directory: *fe
  #     norun: true

  # - title: INFRA
  #   cmd: "  nvim"
  #   working_directory: ../../spectrum-infra/
  #
  # - title: DEPLOY
  #   working_directory: &cdk_dir ../../spectrum-infra/cdk/
  #   cmd: "  AWS_REGION=me-south-1 pnpm cdk deploy -e ..."
  #   norun: true
  #
  # - title: INVOKE
  #   working_directory: *cdk_dir
  #   cmd: "   aws lambda invoke --region me-south-1 --function-name spectrum-migration-runner-spectrummigrationrunnerd-7tvuaaSpJ0HJ /dev/stdout | jq"
  #   norun: true

  # - title: TREE
  #   leftside:
  #     cmd: "  nvim data-loader.py"
  #     working_directory: &dl ../../open-search-data-loader/
  #   rightside:
  #     cmd: "  python data-loader.py data/ | jq -C | less -R"
  #     working_directory: *dl
  #     norun: true

  # - title: T
  #   leftside:
  #     cmd: "  nvim data/"
  #     working_directory: *dl
  #     norun: true
  #   rightside:
  #     upperside:
  #       cmd: |
  #         < data/full-database-v0_3.json jq \
  #         '.hits.hits.[]._source.chapter_code' | sort -V | uniq -c
  #       norun: true
  #       working_directory: *dl
  #     lowerside:
  #       cmd: python data-loader.py data/ > initial-tree-v0_2_5.json
  #       norun: true
