# yaml-language-server: $schema=../schema.json
env: []

windows:
  - title: TEST
    cmd: "  pnpm test"
    working_directory: &fe ../../rex-frontend

  # - title: IDE
  #   cmd: "  nvim"
  #   working_directory: *fe

  - title: IDE
    leftside:
      cmd: "  nvim"
      working_directory: *fe
    rightside:
      cmd: "  pnpm exec tsc --watch"
      working_directory: *fe

  - title: DEV
    leftside:
      cmd: "  pnpm dev"
      working_directory: *fe
    rightside:
      upperside:
        cmd: "  nvim .aws/credentials .env.local"
        working_directory: *fe
      lowerside:
        cmd: "  docker restart rex-aiserver"
        working_directory: *fe
        norun: true

  - title: VMs
    leftside:
      cmd: "  docker compose up"
      working_directory: &vm ../../rex-frontend/.devcontainer
    rightside:
      cmd: "  docker logs -f rex-aiserver"
      working_directory: *vm
      norun: true

  - title: N
    cmd: "  nvim"
    working_directory: ../mzh-notes/

  - title: AI
    cmd: "  nvim"
    working_directory: ../rex-ai

  - title: GIT
    rightside:
      cmd: "  git commit --no-verify"
      working_directory: *fe
      norun: true
    leftside:
      cmd: "  git diff --staged --ignore-all-space | delta"
      working_directory: *fe
      norun: true
# windows:
#   - cmd: "  nvlazy"
#     working_directory: ~/Repositories/A-star
#   - cmd: "echo hi"
#     norun: true
#     working_directory: "~"
#   - title: DEV
#     leftside:
#       cmd: "  pnpm dev"
#       norun: true
#     rightside:
#       upperside:
#         cmd: "  nvlazy .aws/credentials"
#         norun: true
#       lowerside:
#         cmd: "  docker restart rex-aiserver"
#         norun: true
